version: "3.8"
services:
  backend:
    build: ./backend-java
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/backend-java:${PWD}/backend-java"
  frontend:
    build: ./frontend
    working_dir: ${PWD}/frontend
    volumes:
      - "${PWD}/frontend:${PWD}/frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend
